language: python
python:
  - "3.7"
  - "3.8"
os:
  - linux
  - osx
# command to install dependencies
install:
  - python -m pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest