theme: jekyll-theme-cayman

title: <img src="media/images/asb-logo-light.png" alt="AeroSandbox Logo" max-width="500px">
description: A Python package for aircraft design optimization, fully-coupled viscous/inviscid 3D aerodynamics, and reverse-mode automatic differentiation for computing gradients of design variables.
google_analytics: 
show_downloads: true

github:
  zip_url: https://github.com/peterdsharpe/aerosandbox/zipball/master
  tar_url: https://github.com/peterdsharpe/aerosandbox/tarball/master
