theme: jekyll-theme-cayman

title: <img src="media/images/asb-logo-light.png" alt="AeroSandbox Logo" width="600px">
description: Aircraft design optimization, fully-coupled viscous/inviscid 3D aerodynamics, and reverse-mode automatic differentiation for efficiently computing gradients of design variables. Written in Python, work in progress.
google_analytics: 
show_downloads: true

github:
  zip_url: https://github.com/peterdsharpe/aerosandbox/zipball/master
  tar_url: https://github.com/peterdsharpe/aerosandbox/tarball/master
